platform :ios, '10.0'

target 'cyano' do
  
  pod 'YYKit', '~> 1.0.9'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.15'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SAMKeychain', '~> 1.5.3'
  pod 'MMDrawerController', '~> 0.6.0'
  pod 'AFNetworking', '~> 3.2.0'
  pod 'MJExtension', '~> 3.0.15.1'  
  pod 'FMDB'
  pod 'SDWebImage', '~> 4.4.1'
  pod 'libPhoneNumber-iOS'
  pod 'IQKeyboardManager' ,'~> 6.0.6'
  pod 'SVProgressHUD'
  pod 'SDCycleScrollView', '~> 1.75'
end

